<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAmiaOOg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAmiaOOg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAmiaOOg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAmiaOOg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAmiaOOg\App_KernelDevDebugContainer([
    'container.build_hash' => 'AmiaOOg',
    'container.build_id' => 'd41f1875',
    'container.build_time' => 1659676452,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAmiaOOg');
