<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPcLYFRZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPcLYFRZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPcLYFRZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPcLYFRZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPcLYFRZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'PcLYFRZ',
    'container.build_id' => '8f143f73',
    'container.build_time' => 1660739195,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPcLYFRZ');
